title: Joakim Lahtinen
description: Tech and software development
remote_theme: piazzai/cvless
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  linkedin: joakim-lahtinen-67597046
  github: VibyJocke

author:
  name: Joakim Lahtinen
photo: assets/cv_bw_cropped_square.jpg
