title: Joakim Lahtinen
description: Tech and software development
taglong: Tech and software development
tagshort: Tech and software development

remote_theme: piazzai/cvless
url: https://vibyjocke.github.io
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  linkedin: joakim-lahtinen-67597046
  github: VibyJocke

author:
  name: Joakim Lahtinen
photo: assets/cv_bw_cropped_square.jpg
