theme: cvless
title: VibyJocke
description: WIP

social:
  linkedin: https://www.linkedin.com/in/joakim-lahtinen-67597046/
  medium: username
  github: username

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
