title: VibyJocke
description: WIP
remote_theme: piazzai/cvless
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  linkedin: joakim-lahtinen-67597046
  github: VibyJocke
